version: "3.4"

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
    - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
    - "3000:3000"

  loki:
   image: grafana/loki:2.4.2
   container_name: loki
   volumes:
     - ./config/loki-local-config.yaml:/etc/loki/loki-local-config.yaml
   entrypoint:
     - /usr/bin/loki
   command: -config.file=/etc/loki/loki-local-config.yaml
   ports:
     - "3100:3100"

  promtail:
    image: grafana/promtail:2.4.2
    container_name: promtail
    volumes:
      - ./config/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml
      - /var/log/:/var/log/
    command: -config.file=/etc/promtail/promtail-local-config.yaml
